### ISSUE TITLE
Runtime Error No provider for ApplicationInitStatus!

### ISSUE THREAD

**Issue by cbleu** [aaronksaunders/ionic2.0-angularfire#7]
Hi,
i've just clone the repository and update npm and package.json to ionic 3
but when launching the ionic serve i have this error:

```
Runtime Error
No provider for ApplicationInitStatus!
Stack
Error
    at g (http://localhost:8103/build/polyfills.js:3:7133)
    at injectionError (http://localhost:8103/build/main.js:1509:86)
    at noProviderError (http://localhost:8103/build/main.js:1547:12)
    at ReflectiveInjector_._throwOrNull (http://localhost:8103/build/main.js:3048:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:8103/build/main.js:3087:25)
    at ReflectiveInjector_._getByKey (http://localhost:8103/build/main.js:3019:25)
    at ReflectiveInjector_.get (http://localhost:8103/build/main.js:2888:21)
    at AppModuleInjector.NgModuleInjector.get (http://localhost:8103/build/main.js:3835:52)
    at http://localhost:8103/build/main.js:5034:70
    at _callAndReportToErrorHandler (http://localhost:8103/build/main.js:4935:39)
    at http://localhost:8103/build/main.js:5033:20
    at t.invoke (http://localhost:8103/build/polyfills.js:3:14529)
    at Object.onInvoke (http://localhost:8103/build/main.js:4403:37)
    at t.invoke (http://localhost:8103/build/polyfills.js:3:14469)
    at n.run (http://localhost:8103/build/polyfills.js:3:9741)
Ionic Framework: 3.0.1
Ionic App Scripts: 1.3.4
Angular Core: 4.0.3
Angular Compiler CLI: 4.0.3
Node: 7.7.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
```

Here are dependencies of my package.json:
```
  "dependencies": {
    "@angular/common": "4.0.3",
    "@angular/compiler": "4.0.3",
    "@angular/compiler-cli": "4.0.3",
    "@angular/core": "4.0.3",
    "@angular/forms": "4.0.3",
    "@angular/http": "4.0.3",
    "@angular/platform-browser": "4.0.3",
    "@angular/platform-browser-dynamic": "4.0.3",
    "@angular/platform-server": "4.0.3",
    "@ionic/storage": "2.0.1",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.3",
    "@ngrx/store": "^2.2.2",
    "@ngrx/store-devtools": "^3.2.4",
    "angularfire2": "^2.0.0-beta.8",
    "firebase": "^3.9.0",
    "ionic-angular": "3.0.1",
    "@ionic-native/core": "^3.4.2",
    "@ionic-native/facebook": "^3.4.4",
    "@ionic-native/google-plus": "^3.4.4",
    "@ionic-native/splash-screen": "^3.4.2",
    "@ionic-native/status-bar": "^3.4.2",
    "ionicons": "3.0.0",
    "rxjs": "5.3.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.9"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.3.4",
    "typescript": "2.2.2"
  },

```

cheers,
cesar

**Comment by cbleu** [comment]
Ok find the issue, ionic 3 has changed also the app.module.ts and need some change also:

Need to import that in app.modue.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { SplashScreen } from '@ionic-native/splash-screen';
import { StatusBar } from '@ionic-native/status-bar';

```

And add that too in @NgModule:
```
@NgModule({
  imports: [
    ...
    BrowserModule, 
    ...
  ],
```

And add that lines in the providers:
```
  providers: [
    StatusBar,
    SplashScreen,
    { provide: ErrorHandler, useClass: IonicErrorHandler }]
})
```

Sorry for the issue !
now all works fine with ionic3
